regression_metric:
  class_path: models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0.9
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 3.1e-05
    layerwise_decay: 0.95
    encoder_model: BERT
    pretrained_model: microsoft/unixcoder-base
    pool: cls
    layer: mix
    layer_transformation: sparsemax
    layer_norm: True
    loss: mse
    dropout: 0.15
    batch_size: 25
    train_data: 
      - /home/dingjiazheng/projects/58/COMET-master/data.new/train.jsonl
    validation_data: 
      - /home/dingjiazheng/projects/58/COMET-master/data.new/dev.jsonl
    hidden_sizes:
      - 3072
      - 1024
    activations: Tanh
    
trainer: ../trainer.yaml
early_stopping: ../early_stopping.yaml
model_checkpoint: ../model_checkpoint.yaml
